package com.bfw.domain;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_id
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_pw
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private String userPw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_name
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_url
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private String userUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_sex
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private String userSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_age
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private Integer userAge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_phone
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private Integer userPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_beizhu
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private String userBeizhu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_ctime
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private Date userCtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.is_used
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private String isUsed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_anthority
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	private String userAnthority;
	
	  private Integer bespeakId;
	  
	  

	public Integer getBespeakId() {
		return bespeakId;
	}

	public void setBespeakId(Integer bespeakId) {
		this.bespeakId = bespeakId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_id
	 * @return  the value of user_info.user_id
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_id
	 * @param userId  the value for user_info.user_id
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_pw
	 * @return  the value of user_info.user_pw
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public String getUserPw() {
		return userPw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_pw
	 * @param userPw  the value for user_info.user_pw
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_name
	 * @return  the value of user_info.user_name
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_name
	 * @param userName  the value for user_info.user_name
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_url
	 * @return  the value of user_info.user_url
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public String getUserUrl() {
		return userUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_url
	 * @param userUrl  the value for user_info.user_url
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserUrl(String userUrl) {
		this.userUrl = userUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_sex
	 * @return  the value of user_info.user_sex
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public String getUserSex() {
		return userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_sex
	 * @param userSex  the value for user_info.user_sex
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_age
	 * @return  the value of user_info.user_age
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public Integer getUserAge() {
		return userAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_age
	 * @param userAge  the value for user_info.user_age
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_phone
	 * @return  the value of user_info.user_phone
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public Integer getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_phone
	 * @param userPhone  the value for user_info.user_phone
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserPhone(Integer userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_beizhu
	 * @return  the value of user_info.user_beizhu
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public String getUserBeizhu() {
		return userBeizhu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_beizhu
	 * @param userBeizhu  the value for user_info.user_beizhu
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserBeizhu(String userBeizhu) {
		this.userBeizhu = userBeizhu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_ctime
	 * @return  the value of user_info.user_ctime
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public Date getUserCtime() {
		return userCtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_ctime
	 * @param userCtime  the value for user_info.user_ctime
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserCtime(Date userCtime) {
		this.userCtime = userCtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.is_used
	 * @return  the value of user_info.is_used
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public String getIsUsed() {
		return isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.is_used
	 * @param isUsed  the value for user_info.is_used
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setIsUsed(String isUsed) {
		this.isUsed = isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_anthority
	 * @return  the value of user_info.user_anthority
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public String getUserAnthority() {
		return userAnthority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_anthority
	 * @param userAnthority  the value for user_info.user_anthority
	 * @mbggenerated  Wed May 21 13:51:45 CST 2014
	 */
	public void setUserAnthority(String userAnthority) {
		this.userAnthority = userAnthority;
	}

	@Override
	public String toString() {
		return "UserInfo [userId=" + userId + ", userPw=" + userPw
				+ ", userName=" + userName + ", userUrl=" + userUrl
				+ ", userSex=" + userSex + ", userAge=" + userAge
				+ ", userPhone=" + userPhone + ", userBeizhu=" + userBeizhu
				+ ", userCtime=" + userCtime + ", isUsed=" + isUsed
				+ ", userAnthority=" + userAnthority + "]";
	}
	
	
}